name = "quickbg-worker"
compatibility_date = "2024-01-01"
main = "src/index.js"
account_id = "1813a08569eee03a6147d2011d25a607"

[vars]
REMOVE_BG_API_KEY = "{{ secrets.REMOVE_BG_API_KEY }}"

[dev]
port = 8787
local_protocol = "http"
upstream_protocol = "https"

# 环境配置
[env.production]
name = "quickbg-worker-prod"

[env.staging]
name = "quickbg-worker-staging"
